server {
    listen 5173;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /inventory {
        proxy_pass http://192.168.1.200:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /inventory/ {
        proxy_pass http://192.168.1.200:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://192.168.1.200:8002;
    }

    location /admin/ {
        proxy_pass http://192.168.1.200:8002/admin/;
        proxy_set_header Host $host;
    }

    # NUEVO: proxy para obtener información del servidor
    location /guild {
        proxy_pass http://192.168.1.200:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
